# Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
# or more contributor license agreements. Licensed under the Elastic License
# 2.0 and the Server Side Public License, v 1; you may not use this file except
# in compliance with, at your election, the Elastic License 2.0 or the Server
# Side Public License, v 1.

# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: distillate
  description: Theme-agnostic CSS style engine
  links:
    - url: https://github.com/elastic/distillate
      title: GitHub repository
  tags:
    - distillate
    - css
    - typescript
spec:
  type: library
  owner: group:eui-team
  lifecycle: experimental
