/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const checkOnly = process.argv.includes('--check');
const reportPath = join(repoRoot, 'THIRD_PARTY_LICENSES.md');
const noticePath = join(repoRoot, 'NOTICE.txt');

const LICENSE_BASENAMES = [
  'LICENSE',
  'LICENSE.md',
  'LICENSE.txt',
  'LICENCE',
  'LICENCE.md',
  'COPYING',
];

const NOTICE_BASENAMES = ['NOTICE', 'NOTICE.txt', 'NOTICE.md'];

const manifest = JSON.parse(
  readFileSync(join(repoRoot, 'package.json'), 'utf-8')
);

const readPackage = (dir) =>
  JSON.parse(readFileSync(join(dir, 'package.json'), 'utf-8'));

const licenseOf = (pkg) => {
  if (typeof pkg.license === 'string') {
    return pkg.license;
  }
  if (pkg.license && typeof pkg.license === 'object' && pkg.license.type) {
    return pkg.license.type;
  }
  if (Array.isArray(pkg.licenses)) {
    return pkg.licenses
      .map((entry) => (typeof entry === 'string' ? entry : entry.type))
      .filter(Boolean)
      .join(' OR ');
  }
  return 'UNKNOWN';
};

const readFirstExisting = (dir, names) => {
  for (const name of names) {
    const candidate = join(dir, name);
    if (existsSync(candidate)) {
      return readFileSync(candidate, 'utf-8').trim();
    }
  }
  return undefined;
};

const resolvePackageDir = (name, fromDir) => {
  try {
    return dirname(
      require.resolve(`${name}/package.json`, { paths: [fromDir] })
    );
  } catch {
    // Some packages hide package.json behind `exports`.
  }

  try {
    let dir = dirname(require.resolve(name, { paths: [fromDir] }));
    while (dir !== dirname(dir)) {
      const candidate = join(dir, 'package.json');
      if (existsSync(candidate)) {
        const pkg = readPackage(dir);
        if (pkg.name === name) {
          return dir;
        }
      }
      dir = dirname(dir);
    }
  } catch {
    return undefined;
  }
  return undefined;
};

const isPlatformPackage = (pkg) =>
  (Array.isArray(pkg.os) && pkg.os.length > 0) ||
  (Array.isArray(pkg.cpu) && pkg.cpu.length > 0);

const walk = (name, fromDir, seen) => {
  const dir = resolvePackageDir(name, fromDir);
  if (dir === undefined || seen.has(dir)) {
    return;
  }

  const pkg = readPackage(dir);
  // Omit `os`/`cpu`-restricted packages so the committed report is host-independent.
  if (isPlatformPackage(pkg)) {
    return;
  }

  seen.set(dir, {
    name: pkg.name ?? name,
    version: pkg.version ?? 'unknown',
    license: licenseOf(pkg),
    path: relative(repoRoot, dir) || '.',
    licenseText: readFirstExisting(dir, LICENSE_BASENAMES),
    noticeText: readFirstExisting(dir, NOTICE_BASENAMES),
  });

  for (const dep of [
    ...Object.keys(pkg.dependencies ?? {}),
    ...Object.keys(pkg.optionalDependencies ?? {}),
  ]) {
    walk(dep, dir, seen);
  }
};

const collect = (names) => {
  const seen = new Map();
  for (const name of names) {
    walk(name, repoRoot, seen);
  }
  return [...seen.values()].sort(
    (a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version)
  );
};

const runtimeRows = collect(Object.keys(manifest.dependencies ?? {}));
const sourceRows = collect(Object.keys(manifest.devDependencies ?? {}));

const table = (rows) => [
  '| Package | Version | SPDX | Path |',
  '| --- | --- | --- | --- |',
  ...rows.map(
    (row) =>
      `| \`${row.name}\` | ${row.version} | ${row.license} | \`${row.path}\` |`
  ),
];

const report = [
  '# Third-party licenses',
  '',
  'Source and distribution dependency closures of `@elastic/distillate`. Regenerated by `pnpm licenses:report`.',
  '',
  '## Distribution (runtime)',
  '',
  'Packages a consumer installs with this library. Their license texts are folded into `NOTICE.txt`.',
  '',
  ...table(runtimeRows),
  '',
  '## Source and build',
  '',
  'Direct `devDependencies` and their installed dependency closure. These are not distributed in the published tarball.',
  '',
  ...table(sourceRows),
  '',
].join('\n');

const noticeBlocks = runtimeRows.map((row) => {
  const heading = `This product depends on ${row.name}@${row.version}, licensed under ${row.license}.`;
  const parts = [heading];
  if (row.noticeText !== undefined) {
    parts.push('', row.noticeText);
  }
  if (row.licenseText !== undefined) {
    parts.push('', row.licenseText);
  }
  if (row.noticeText === undefined && row.licenseText === undefined) {
    parts.push(
      '',
      'No LICENSE or NOTICE file was present in the installed package.'
    );
  }
  return parts.join('\n');
});

const notice = [
  'Distillate',
  'Copyright 2026 Elasticsearch B.V.',
  '',
  'This NOTICE includes the notices and license texts of runtime dependencies shipped alongside this product.',
  ...(noticeBlocks.length > 0
    ? ['', '---', '', noticeBlocks.join('\n\n---\n\n')]
    : []),
  '',
].join('\n');

const writeOrCheck = (path, contents, label) => {
  if (checkOnly) {
    if (!existsSync(path)) {
      console.error(
        `${label} is missing. Run \`pnpm licenses:report\` to generate it.`
      );
      return false;
    }
    if (readFileSync(path, 'utf-8') !== contents) {
      console.error(
        `${label} is out of date. Run \`pnpm licenses:report\` and commit the result.`
      );
      return false;
    }
    return true;
  }
  writeFileSync(path, contents);
  return true;
};

const reportOk = writeOrCheck(reportPath, report, 'THIRD_PARTY_LICENSES.md');
const noticeOk = writeOrCheck(noticePath, notice, 'NOTICE.txt');

if (checkOnly) {
  if (!reportOk || !noticeOk) {
    process.exit(1);
  }
  console.log(
    `License report check passed: ${runtimeRows.length} runtime, ${sourceRows.length} source/build.`
  );
  process.exit(0);
}

console.log(
  `Wrote ${reportPath} and ${noticePath} (${runtimeRows.length} runtime, ${sourceRows.length} source/build).`
);
